/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M10
 * Generated at: 2017-03-01 07:14:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("jar:file:/C:/Users/Hari/Desktop/Scheduler-Under-Progress-master/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/schedulerFrontEnd/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("jar:file:/C:/Users/Hari/Desktop/Scheduler-Under-Progress-master/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/schedulerFrontEnd/WEB-INF/lib/spring-webmvc-4.3.1.RELEASE.jar!/META-INF/spring-form.tld", Long.valueOf(1467602630000L));
    _jspx_dependants.put("jar:file:/C:/Users/Hari/Desktop/Scheduler-Under-Progress-master/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/schedulerFrontEnd/WEB-INF/lib/spring-webmvc-4.3.1.RELEASE.jar!/META-INF/spring.tld", Long.valueOf(1467602630000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-webmvc-4.3.1.RELEASE.jar", Long.valueOf(1474631126483L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1474631165201L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<!-- Latest compiled and minified CSS -->\r\n");
      out.write("<link rel=\"stylesheet\"\r\n");
      out.write("\thref=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery library -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- Latest compiled JavaScript -->\r\n");
      out.write("<script\r\n");
      out.write("\tsrc=\"http://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Scheduler</title>\r\n");
      out.write("<!-- Bootstrap Core CSS -->\r\n");
      out.write("<link href=\"resources/css/bootstrap.min.css\" rel='stylesheet'\r\n");
      out.write("\ttype='text/css' />\r\n");
      out.write("<!-- Custom CSS -->\r\n");
      out.write("<link href=\"resources/css/style.css\" rel='stylesheet' type='text/css' />\r\n");
      out.write("<!-- jQuery -->\r\n");
      out.write("<link\r\n");
      out.write("\thref='//fonts.googleapis.com/css?family=Roboto:700,500,300,100italic,100,400'\r\n");
      out.write("\trel='stylesheet' type='text/css' />\r\n");
      out.write("<link href='//fonts.googleapis.com/css?family=Montserrat:400,700'\r\n");
      out.write("\trel='stylesheet' type='text/css'>\r\n");
      out.write("<!-- lined-icons -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"resources/css/icon-font.min.css\"\r\n");
      out.write("\ttype='text/css' />\r\n");
      out.write("\r\n");
      out.write("<!-- //lined-icons -->\r\n");
      out.write("<script src=\"resources/js/jquery-1.10.2.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("body {\r\n");
      out.write("\tposition: relative;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section1 {\r\n");
      out.write("\tpadding-top: 50px;\r\n");
      out.write("\theight: 500px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tbackground-color: #1E88E5;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section2 {\r\n");
      out.write("\tpadding-top: 50px;\r\n");
      out.write("\theight: 500px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tbackground-color: #673ab7;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section3 {\r\n");
      out.write("\tpadding-top: 50px;\r\n");
      out.write("\theight: 500px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tbackground-color: #ff9800;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#section4 {\r\n");
      out.write("\tpadding-top: 50px;\r\n");
      out.write("\theight: 500px;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tbackground-color: #00bcd4;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\"navbar navbar-inverse navbar-fixed-top\">\r\n");
      out.write("\t<div class=\"container-fluid\">\r\n");
      out.write("\t\t<div class=\"navbar-header\">\r\n");
      out.write("\t\t\t<button type=\"button\" class=\"navbar-toggle\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\tdata-target=\"#myNavbar\">\r\n");
      out.write("\t\t\t\t<span class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("\t\t\t\t\tclass=\"icon-bar\"></span>\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\">Scheduler</a>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"myNavbar\">\r\n");
      out.write("\t\t\t\t<ul class=\"nav navbar-nav\">\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#section1\">Home</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#section2\">About</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"contacts\">Contact</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"#section4\">Footer</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"loginhere\">LogIn</a></li>\r\n");
      out.write("\t\t\t\t\t<li><a href=\"register\">SignUp</a></li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\t<div id=\"section1\" class=\"container-fluid\">\r\n");
      out.write("\t\t<h1>Carousel</h1>\r\n");
      out.write("\t\t<p>Space for carousel.</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"section2\" class=\"container-fluid\">\r\n");
      out.write("\t\t<h1>About</h1>\r\n");
      out.write("\t\t<p>Space for about.</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"section3\" class=\"container-fluid\">\r\n");
      out.write("\t\t<h1>Contact</h1>\r\n");
      out.write("\t\t<p>Space for Contact.</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div id=\"section4\" class=\"container-fluid\">\r\n");
      out.write("\t\t<h1>Footer</h1>\r\n");
      out.write("\t\t<p>Space for footer.</p>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(document).ready(function() {\r\n");
      out.write("\t\t\t// Add scrollspy to <body>\r\n");
      out.write("\t\t\t$('body').scrollspy({\r\n");
      out.write("\t\t\t\ttarget : \".navbar\",\r\n");
      out.write("\t\t\t\toffset : 50\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\r\n");
      out.write("\t\t\t// Add smooth scrolling on all links inside the navbar\r\n");
      out.write("\t\t\t$(\"#myNavbar a\").on('click', function(event) {\r\n");
      out.write("\t\t\t\t// Make sure this.hash has a value before overriding default behavior\r\n");
      out.write("\t\t\t\tif (this.hash !== \"\") {\r\n");
      out.write("\t\t\t\t\t// Prevent default anchor click behavior\r\n");
      out.write("\t\t\t\t\tevent.preventDefault();\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// Store hash\r\n");
      out.write("\t\t\t\t\tvar hash = this.hash;\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t// Using jQuery's animate() method to add smooth page scroll\r\n");
      out.write("\t\t\t\t\t// The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area\r\n");
      out.write("\t\t\t\t\t$('html, body').animate({\r\n");
      out.write("\t\t\t\t\t\tscrollTop : $(hash).offset().top\r\n");
      out.write("\t\t\t\t\t}, 800, function() {\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t// Add hash (#) to URL when done scrolling (default click behavior)\r\n");
      out.write("\t\t\t\t\t\twindow.location.hash = hash;\r\n");
      out.write("\t\t\t\t\t});\r\n");
      out.write("\t\t\t\t} // End if\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
